const answers={};let page=0,finished=false,selected='S',elapsed=0;const started=Date.now();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const input=(key,label='Odpověď:',unit='')=>`<label class="answer">${label}<input type="text" name="${key}" value="${esc(answers[key])}" autocomplete="off" inputmode="decimal" ${finished?'readonly':''}>${unit}</label>`;
function choice(key,value,text){return `<label class="choice"><input type="radio" name="${key}" value="${value}" ${answers[key]===value?'checked':''} ${finished?'disabled':''}><span class="bubble">${value}</span><span>${text}</span></label>`;}
const options=(key,items)=>`<div class="options">${items.map((t,i)=>choice(key,'ABCD'[i],t)).join('')}</div>`;
const frac=(a,b)=>`<span class="frac"><span>${a}</span><span>${b}</span></span>`;
const required=[['q1'],['q2'],['q3'],['q4'],['q5'],['q6'],['q7'],['angleB','angleC','angleD','angleE'],['snailS','snailT'],['q10'],['q11a','q11b']];
const solutions=['9 000 m. Při zaokrouhlení 8 848 na tisíce dostaneme 9 000.','C: 42. Je sudé a zároveň 6 × 7.','1 872.','Ano. Katka může vytáhnout zbývající kartu 7: 4 + 7 = 11, což je více než 10. Vysvětlení se neboduje.','1,25 litru (také 1.25 nebo 5/4). Polovina a tři čtvrtiny jsou dohromady pět čtvrtin.','C: násobení. 9 × 3 = 27 a 32 − 5 = 27.','A: 8 · h = 120.','B: větší než pravý; C: menší než pravý; D: větší než pravý; E: pravý.','S patří na poslední bod vpravo, T na předposlední bod vpravo.','B. Síť má šest bočních stěn a dvě šestiúhelníkové podstavy na opačných stranách pásu.','A: 130 kusů (60 jablek + 30 hrušek + 40 banánů). B: 120 jablek, možnost B.'];
function angles(){return `<img class="figure angles" src="assets/angles.png" alt="Úhly A až E vyznačené na lomené čáře ve čtvercové síti."><p>Urči typ každého úhlu na obrázku. Zapiš své odpovědi do tabulky.</p><p>Úhel A máš udělán jako příklad.</p><table class="angle-table"><thead><tr><th>Úhel</th><th>Pravý úhel</th><th>Menší než pravý úhel</th><th>Větší než pravý úhel</th></tr></thead><tbody><tr class="example"><th>A</th><td><span class="bubble" style="width:36px;margin:auto">A</span></td><td>—</td><td>—</td></tr>${['B','C','D','E'].map(a=>`<tr><th scope="row">${a}</th>${['A','B','C'].map((v,i)=>`<td><label class="choice"><input type="radio" name="angle${a}" value="${v}" aria-label="Úhel ${a}: ${['pravý','menší než pravý','větší než pravý'][i]}" ${answers['angle'+a]===v?'checked':''} ${finished?'disabled':''}><span class="bubble">${v}</span></label></td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const points=[[30,62],[77,50],[125,40],[174,40],[222,40],[266,61],[312,75],[361,69],[406,58],[455,58],[504,58]];
function board(){return `<div class="snail-board"><svg viewBox="0 0 560 160" role="group" aria-label="Cestička s 11 body. Trojúhelník je pod sedmým bodem, kosočtverec pod čtvrtým bodem zleva."><path d="M30 62 C75 58 72 36 125 40 L222 40 C251 40 248 61 266 61 Q295 85 312 75 L361 69 Q380 53 406 58 L504 58" fill="none" stroke="black" stroke-width="2"/>${points.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="4" fill="black"/><g class="point" data-point="${i}" role="button" tabindex="${finished?-1:0}" aria-label="Bod ${i+1} zleva"><circle cx="${x}" cy="${y}" r="20"/><title>Bod ${i+1} zleva</title></g>`).join('')}<text x="164" y="76">◆</text><text x="301" y="106">▲</text>${['S','T'].map(t=>answers['snail'+t]!==undefined?`<text x="${points[Number(answers['snail'+t])][0]}" y="${t==='S'?25:137}" text-anchor="middle" fill="${t==='S'?'#417414':'#176da5'}" font-weight="bold">${t}</text>`:'').join('')}</svg></div>`;}
function snails(){return `<p>Na obrázku dole je cestička, kterou používají šneci. Šneci se mohou pohybovat doleva nebo doprava. Vzdálenost mezi dvěma puntíky na cestičce je jedna jednotka.</p>${board()}<div class="snail-controls" aria-label="Značky šneků">${['S','T'].map(t=>`<button type="button" class="token ${selected===t?'selected':''}" data-token="${t}" aria-pressed="${selected===t}" ${finished?'disabled':''}>${t}</button>`).join('')}</div><p class="snail-hint">Přetáhni písmeno na bod. Můžeš také vybrat písmeno a kliknout na bod; klávesnicí použij Tab a Enter.</p><p>Na cestičce jsou šneci S a T.</p><p><b class="sub">A.</b>Šnek S začíná v ▲. Posune se o 4 jednotky doprava. Kde skončí?</p><p>Přetažením písmene S označ tento bod na cestičce.</p><p><b class="sub">B.</b>Šnek T skončí v ◆. Předtím se posunul o 6 jednotek doleva. Kde šnek začal?</p><p>Přetažením písmene T označ tento bod na cestičce.</p>`;}
const screens=[
()=>`<p>Mount Everest je vysoký 8 848 metrů.</p><p>Zaokrouhli tuto výšku na tisíce.</p>${input('q1','Odpověď:','m')}`,
()=>`<p>Které číslo je <b>sudé a zároveň násobkem 7</b>?</p>${options('q2',['21','24','42','77'])}`,
()=>`<p>6 · 312 =</p>${input('q3')}`,
()=>`<p>Marek a Katka hrají hru, při které používají těchto 8 karet.</p><div class="cards">${[1,2,3,4,5,6,7,8].map(n=>`<span>${n}</span>`).join('')}</div><p>Položí karty lícem dolů tak, že čísla nejsou vidět. Pak si každý hráč vytáhne 2 karty. Hráč s větším součtem vyhrává.</p><p>Marek si vytáhne kartu 8 a kartu 2. Součet je 10.</p><p>Katka si jako první vytáhne kartu 4.</p><p>Může Katka hru vyhrát?<br>(Označ jeden čtvereček.)</p>${options('q4',['Ano','Ne'])}<label>Vysvětli svou odpověď.<textarea name="explanation" ${finished?'readonly':''}>${esc(answers.explanation)}</textarea></label>`,
()=>`<p>Zdena má ${frac(1,2)} litru pomerančového džusu a Karel má ${frac(3,4)} litru pomerančového džusu.</p><p>Kolik litrů pomerančového džusu mají Zdena a Karel dohromady?</p>${input('q5')}`,
()=>`<p>Které znaménko by mělo být v políčku, aby byl zápis pravdivý?</p><p>9 ☐ 3 = 32 − 5</p>${options('q6',['+','−','·',':'])}`,
()=>`<p>Fotbalová liga má celkem 120 hráčů.<br>Je v ní 8 týmů a v každém z nich <i>h</i> hráčů.</p><p>Který zápis popisuje tuto situaci?</p>${options('q7',['8 · <i>h</i> = 120','8 : <i>h</i> = 120','<i>h</i> = 8 · 120','<i>h</i> = 120 + 8'])}`,
angles,snails,
()=>`<p>Jitka chce vyrobit z tvrdého papíru krabičku, jako je ta na obrázku.</p><img class="figure box" src="assets/box.png" alt="Krabička ve tvaru šestibokého hranolu."><p>Ze kterého kousku tvrdého papíru může Jitka složit tuto krabičku?</p><div class="options nets">${['A','B','C','D'].map(v=>choice('q10',v,`<img src="assets/net-${v.toLowerCase()}.png" alt="Síť krabičky – varianta ${v}">`)).join('')}</div>`,
()=>`<p>Majitel obchodu s ovocem sledoval počet jablek, hrušek a banánů prodaných v pondělí.</p><img class="figure fruit" src="assets/fruit.png" alt="Pondělní prodej: 6 obrázků jablka, 3 obrázky hrušky, 4 obrázky banánu. Každý obrázek představuje 10 kusů příslušného ovoce."><p><b class="sub">A.</b>Kolik kusů ovoce se prodalo v pondělí?</p>${input('q11a')}<p style="margin-top:25px"><b class="sub">B.</b>Majitel řekl: „V úterý jsem prodal dvakrát tolik jablek jako v pondělí.“</p><p>Kolik jablek prodal majitel v úterý?</p>${options('q11b',['180','120','18','12'])}`
];
function render(focus=true){$('#heading').textContent=`${finished?'Prohlížení · ':''}Úloha ME2_${String(page+1).padStart(2,'0')}`;$('#count').textContent=`${page+1} / 11`;$('#question').innerHTML=`<span class="qid">${TIMSS.ids[page]}</span>${screens[page]()}${finished?`<div class="feedback"><b>Správná odpověď</b><p>${solutions[page]}</p></div>`:''}`;$('#prev').disabled=page===0;$('#next').disabled=page===10;$('#finish').textContent=finished?'Zpět na výsledek':'Odevzdat test';if(focus)$('#question').focus();bindSnails();}
$('#question').addEventListener('input',e=>{if(!finished&&e.target.name)answers[e.target.name]=e.target.value;});
$('#prev').onclick=()=>{if(page>0){page--;render();}};$('#next').onclick=()=>{if(page<10){page++;render();}};
function place(i){if(finished)return;answers['snail'+selected]=String(i);render(false);}
function bindSnails(){if(page!==8||finished)return;document.querySelectorAll('[data-point]').forEach(el=>{el.onclick=()=>place(el.dataset.point);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(el.dataset.point);}};});document.querySelectorAll('[data-token]').forEach(el=>{el.onclick=()=>{selected=el.dataset.token;render(false);};el.onpointerdown=e=>{selected=el.dataset.token;el.setPointerCapture(e.pointerId);};el.onpointerup=e=>{const board=$('.snail-board svg'),rect=board.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*560,y=(e.clientY-rect.top)/rect.height*160;let best=-1,dist=Infinity;points.forEach(([px,py],i)=>{const d=Math.hypot(px-x,py-y);if(d<dist){dist=d;best=i;}});if(dist<35){place(best);}else{document.querySelectorAll('[data-token]').forEach(b=>{b.classList.toggle('selected',b.dataset.token===selected);b.setAttribute('aria-pressed',String(b.dataset.token===selected));});}};});}
$('#finish').onclick=()=>{if(finished){result();return;}const missing=required.filter(keys=>keys.some(k=>answers[k]===undefined||String(answers[k]).trim()==='')).length;$('#confirm-text').textContent=missing?`V ${missing} z 11 úloh ještě chybí odpověď nebo její část. Nevyplněné odpovědi nezískají bod. Chceš test přesto odevzdat?`:'Máš vyplněné všechny úlohy. Po odevzdání už odpovědi nepůjde měnit.';$('#confirm').showModal();};$('#cancel').onclick=()=>$('#confirm').close();$('#submit').onclick=()=>{$('#confirm').close();finished=true;elapsed=Math.floor((Date.now()-started)/1000);result();};
function result(){const scores=TIMSS.score(answers),sum=scores.reduce((a,b)=>a+b,0),percent=(sum/12*100).toLocaleString('cs-CZ',{maximumFractionDigits:1});$('#heading').textContent='Ranní matematika · Výsledek testu'.replace('Ranní matematika','TIMSS 2023');$('#count').textContent='ME2 · 11 úloh';$('#question').innerHTML=`<section class="result"><h1>${TIMSS.grade(sum)}</h1><div class="percent">${percent} %</div><p>Získal/a jsi <b>${sum} z 12 bodů</b>.</p><p class="small">Čas řešení: ${formatTime(elapsed)}. Motivační hodnocení tohoto cvičného testu.</p><table class="result-table"><thead><tr><th>Úloha</th><th>Body</th><th></th></tr></thead><tbody>${TIMSS.ids.map((id,i)=>`<tr><td>${i+1}. ${id}</td><td>${i===10?scores[10]+scores[11]:scores[i]} / ${i===10?2:1}</td><td><button data-review="${i}">Prohlédnout</button></td></tr>`).join('')}</tbody></table><div class="result-actions"><button id="print">Vytisknout výsledek</button><button id="again">Nový pokus</button></div></section>`;$('#prev').disabled=true;$('#next').disabled=true;$('#finish').textContent='Výsledek testu';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{page=Number(b.dataset.review);render();});$('#print').onclick=()=>window.print();$('#again').onclick=()=>{if(window.confirm('Začít nový pokus? Aktuální odpovědi a výsledek se vymažou.'))location.reload();};$('#question').focus();}
function formatTime(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;}setInterval(()=>{if(!finished)$('#timer').textContent=formatTime(Math.floor((Date.now()-started)/1000));},1000);render(false);
if(document.modelContext?.registerTool){
for(const tool of [
{name:'read_test_progress',description:'Read the current task number and completion state without revealing correct answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({task:page+1,submitted:finished,completedTasks:required.filter(keys=>keys.every(k=>answers[k]!==undefined&&String(answers[k]).trim()!=='')).length,totalTasks:11,...(finished?{points:TIMSS.score(answers).reduce((a,b)=>a+b,0),maximumPoints:12}:{})})},
{name:'go_to_test_task',description:'Navigate to a task from 1 through 11, retaining current answers. Does not submit the test.',inputSchema:{type:'object',properties:{task:{type:'integer',minimum:1,maximum:11}},required:['task'],additionalProperties:false},execute:({task})=>{if(!Number.isInteger(task)||task<1||task>11)throw new Error('Task must be 1–11.');page=task-1;render();return {task};}}
]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}
