function choice(key,value,text){return `<label class="choice"><input type="radio" name="${key}" value="${value}" ${answers[key]===value?'checked':''} ${finished?'disabled':''}><span class="bubble">${value}</span><span>${text}</span></label>`;}
const options=(key,items)=>`<div class="options" role="group">${items.map((t,i)=>choice(key,'ABCD'[i],t)).join('')}</div>`;
const frac=(a,b)=>`<span class="frac"><span>${a}</span><span>${b}</span></span>`;
const required=[['q1'],['q2'],['q3'],['q4'],['q5'],['q6'],['q7'],['angleB','angleC','angleD','angleE'],['snailS','snailT'],['q10'],['q11a','q11b']];
const solutions=['9 000 m. Při zaokrouhlení 8 848 na tisíce dostaneme 9 000.','C: 42. Je sudé a zároveň 6 × 7.','1 872.','Ano. Katka může vytáhnout zbývající kartu 7: 4 + 7 = 11, což je více než 10. Vysvětlení se neboduje.','1,25 litru (také 1.25 nebo 5/4). Polovina a tři čtvrtiny jsou dohromady pět čtvrtin.','C: násobení. 9 × 3 = 27 a 32 − 5 = 27.','A: 8 × h = 120.','B: větší než pravý; C: menší než pravý; D: větší než pravý; E: pravý.','S patří na poslední bod vpravo, T na předposlední bod vpravo.','B. Síť má šest bočních stěn a dvě šestiúhelníkové podstavy na opačných stranách pásu.','A: 130 kusů (60 jablek + 30 hrušek + 40 banánů). B: 120 jablek, možnost B.'];
function angles(){return `<img class="figure angles" src="assets/angles.png" alt="Úhly A až E vyznačené na lomené čáře ve čtvercové síti."><p>Urči typ každého úhlu na obrázku. Zapiš své odpovědi do tabulky.</p><p>Úhel A máš udělán jako příklad.</p><table class="angle-table"><thead><tr><th>Úhel</th><th>Pravý úhel</th><th>Menší než pravý úhel</th><th>Větší než pravý úhel</th></tr></thead><tbody><tr class="example"><th>A</th><td><span class="bubble" style="width:36px;margin:auto">A</span></td><td>—</td><td>—</td></tr>${['B','C','D','E'].map(a=>`<tr><th scope="row">${a}</th>${['A','B','C'].map((v,i)=>`<td><label class="choice"><input type="radio" name="angle${a}" value="${v}" aria-label="Úhel ${a}: ${['pravý','menší než pravý','větší než pravý'][i]}" ${answers['angle'+a]===v?'checked':''} ${finished?'disabled':''}><span class="bubble">${v}</span></label></td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const points=[[30,62],[77,50],[125,40],[174,40],[222,40],[266,61],[312,75],[361,69],[406,58],[455,58],[504,58]];
function board(){return `<div class="test-snail-board" id="snail-board"><svg viewBox="0 0 560 280" aria-label="Zahnutá cestička s jedenácti body. Trojúhelník je u sedmého bodu, kosočtverec u čtvrtého bodu zleva."><path d="M30 142 C75 138 72 116 125 120 L222 120 C251 120 248 141 266 141 Q295 165 312 155 L361 149 Q380 133 406 138 L504 138" fill="none" stroke="#536580" stroke-width="3"/>${points.map(([x,y],i)=>`<g class="test-point" data-point="${i}" role="button" tabindex="${finished?-1:0}" aria-label="Bod ${i+1} zleva"><circle cx="${x}" cy="${y+80}" r="17" fill="transparent"/><circle cx="${x}" cy="${y+80}" r="4" fill="#35445e"/></g>`).join('')}<text x="174" y="151" text-anchor="middle" font-size="21" fill="#35445e">◆</text><text x="312" y="186" text-anchor="middle" font-size="21" fill="#35445e">▲</text></svg>${['S','T'].map(t=>{const i=answers['snail'+t];return `<button class="test-snail ${selected===t?'selected':''}" data-snail="${t}" style="left:${i===undefined?(t==='S'?27:72):points[Number(i)][0]/560*100}%;top:${t==='S'?3:72}%" aria-label="Šnek ${t}, ${t==='S'?'modrý':'oranžový'}, ${i===undefined?'zatím neumístěn':'bod '+(Number(i)+1)}" aria-pressed="${selected===t}" ${finished?'disabled':''}><img src="assets/snek-${t.toLowerCase()}.png" alt="" draggable="false"><span>${t}</span></button>`;}).join('')}</div>`;}
function snails(){return `<p>Šneci se pohybují po cestičce doleva nebo doprava. Vzdálenost mezi dvěma sousedními body je jedna jednotka.</p>${board()}<p class="subtle" id="snail-status">${snailStatus()}</p><p><b class="sub">A.</b><b>Modrý šnek S</b> vyšel z bodu označeného ▲ a posunul se o <b>4 jednotky doprava</b>.<br>Přetáhni modrého šneka na bod, kde skončil.</p><p><b class="sub">B.</b><b>Oranžový šnek T</b> se posunul o <b>6 jednotek doleva</b> a skončil v bodě označeném ◆.<br>Přetáhni oranžového šneka na bod, odkud vyšel.</p><p class="subtle">Chytni obrázek šneka, přetáhni ho k bodu a pusť. Také můžeš kliknout na šneka a potom na bod; klávesnicí použij Tab a Enter.</p>`;}
const screens=[
()=>`<p>Mount Everest je vysoký 8 848 metrů.</p><p>Zaokrouhli tuto výšku na tisíce.</p>${input('q1','Odpověď:','m')}`,
()=>`<p>Které číslo je <b>sudé a zároveň násobkem 7</b>?</p>${options('q2',['21','24','42','77'])}`,
()=>`<p>6 × 312 =</p>${input('q3')}`,
()=>`<p>Marek a Katka hrají hru, při které používají těchto 8 karet.</p><div class="cards">${[1,2,3,4,5,6,7,8].map(n=>`<span>${n}</span>`).join('')}</div><p>Položí karty lícem dolů tak, že čísla nejsou vidět. Pak si každý hráč vytáhne 2 karty. Hráč s větším součtem vyhrává.</p><p>Marek si vytáhne kartu 8 a kartu 2. Součet je 10.</p><p>Katka si jako první vytáhne kartu 4.</p><p>Může Katka hru vyhrát?<br>(Označ jeden čtvereček.)</p>${options('q4',['Ano','Ne'])}<label>Vysvětli svou odpověď.<textarea name="explanation" ${finished?'readonly':''}>${esc(answers.explanation)}</textarea></label>`,
()=>`<p>Zdena má ${frac(1,2)} litru pomerančového džusu a Karel má ${frac(3,4)} litru pomerančového džusu.</p><p>Kolik litrů pomerančového džusu mají Zdena a Karel dohromady?</p>${input('q5')}`,
()=>`<p>Které znaménko by mělo být v políčku, aby byl zápis pravdivý?</p><p>9 ☐ 3 = 32 − 5</p>${options('q6',['+','−','×',':'])}`,
()=>`<p>Fotbalová liga má celkem 120 hráčů.<br>Je v ní 8 týmů a v každém z nich <i>h</i> hráčů.</p><p>Který zápis popisuje tuto situaci?</p>${options('q7',['8 × <i>h</i> = 120','8 : <i>h</i> = 120','<i>h</i> = 8 × 120','<i>h</i> = 120 + 8'])}`,
angles,snails,
()=>`<p>Jitka chce vyrobit z tvrdého papíru krabičku, jako je ta na obrázku.</p><img class="figure box" src="assets/box.png" alt="Krabička ve tvaru šestibokého hranolu."><p>Ze kterého kousku tvrdého papíru může Jitka složit tuto krabičku?</p><div class="options nets">${['A','B','C','D'].map(v=>choice('q10',v,`<img src="assets/net-${v.toLowerCase()}.png" alt="Síť krabičky – varianta ${v}">`)).join('')}</div>`,
()=>`<p>Majitel obchodu s ovocem sledoval počet jablek, hrušek a banánů prodaných v pondělí.</p><img class="figure fruit" src="assets/fruit.png" alt="Pondělní prodej: 6 obrázků jablka, 3 obrázky hrušky, 4 obrázky banánu. Každý obrázek představuje 10 kusů příslušného ovoce."><p><b class="sub">A.</b>Kolik kusů ovoce se prodalo v pondělí?</p>${input('q11a')}<p style="margin-top:25px"><b class="sub">B.</b>Majitel řekl: „V úterý jsem prodal dvakrát tolik jablek jako v pondělí.“</p><p>Kolik jablek prodal majitel v úterý?</p>${options('q11b',['180','120','18','12'])}`
];
