function answered(i){return required[i].every(k=>{const a=String(answers[k]??'').trim();return a!==''&&(!a.includes('/')||a.split('/').every(s=>s.trim()!==''));});}
function renderSteps(){const rail=$('#steps');rail.innerHTML=TIMSS.ids.map((id,i)=>`<li class="${answered(i)?'done':''}"><button data-step="${i}" ${!finished&&i>unlocked?'disabled':''} ${page===i?'aria-current="step"':''} aria-label="Otázka ${i+1}${answered(i)?', odpovězeno':''}"><span class="circle">${i+1}</span><span class="step-name">Otázka ${i+1}</span></button></li>`).join('');rail.querySelectorAll('button').forEach(b=>b.onclick=()=>go(Number(b.dataset.step)));$('#progress').textContent=`Vyplněno ${TIMSS.ids.filter((_,i)=>answered(i)).length} z 11 úloh.`;}
function go(i){if(i<0||i>10||(!finished&&i>unlocked))return;closePad();page=i;render();}
function render(focus=true){renderSteps();$('#question').innerHTML=`<div class="question-header"><span class="eyebrow">${finished?'Prohlížení odpovědí':'Otázka '+(page+1)+' z 11'}</span><span class="qid">${TIMSS.ids[page]}</span></div><h1 class="task-heading">${['Zaokrouhli výšku','Vyber číslo','Vypočítej','Kdo vyhraje?','Pomerančový džus','Doplň znaménko','Fotbalová liga','Poznej úhly','Šneci na cestičce','Papírová krabička','Prodej ovoce'][page]}</h1>${screens[page]()}${finished?`<div class="review-answer"><b>Správná odpověď</b><p>${solutions[page]}</p></div>`:''}`;$('#prev').disabled=page===0;$('#next').hidden=false;$('#next').disabled=page===10;$('#finish').textContent=finished?'Zpět na výsledek':'Odevzdat test';$('#pad-toggle').disabled=finished||![0,2,4,10].includes(page);if(!finished)bindNumberFields();bindSnails();if(focus)$('#question').focus();}
$('#question').addEventListener('input',e=>{if(!finished&&e.target.name){answers[e.target.name]=e.target.value;renderSteps();}});
$('#prev').onclick=()=>go(page-1);$('#next').onclick=()=>{if(page<10){unlocked=Math.max(unlocked,page+1);go(page+1);}};
$('#finish').onclick=()=>{closePad();if(finished){result();return;}const missing=TIMSS.ids.filter((_,i)=>!answered(i)).length;$('#confirm-text').textContent=missing?`V ${missing} z 11 úloh chybí odpověď nebo její část. Chceš test přesto odevzdat?`:'Máš vyplněné všechny úlohy. Chceš test odevzdat?';$('#confirm').showModal();};$('#cancel').onclick=()=>$('#confirm').close();$('#submit').onclick=()=>{if(finished)return;$('#confirm').close();closePad();elapsed=Math.floor((Date.now()-started)/1000);finished=true;$('#timer').textContent=formatTime(elapsed);result();};
function result(){closePad();renderSteps();const scores=TIMSS.score(answers),sum=scores.reduce((a,b)=>a+b,0),percent=(sum/12*100).toLocaleString('cs-CZ',{maximumFractionDigits:1});$('#question').innerHTML=`<section class="result"><span class="eyebrow">Výsledek testu</span><h1>${TIMSS.grade(sum)}</h1><div class="percent">${percent} %</div><div class="result-stats"><p>Získal/a jsi <b>${sum} z 12 bodů</b>.</p><p>Čas řešení <b>${formatTime(elapsed)}</b></p></div><p class="subtle">Čas je uveden v minutách a sekundách.</p><table class="result-table"><thead><tr><th>Úloha</th><th>Body</th><th></th></tr></thead><tbody>${TIMSS.ids.map((id,i)=>`<tr><td>${i+1}. <span class="subtle">${id}</span></td><td>${i===10?scores[10]+scores[11]:scores[i]} / ${i===10?2:1}</td><td><button class="secondary" data-review="${i}">Prohlédnout</button></td></tr>`).join('')}</tbody></table><div class="row result-actions"><button id="print" class="primary">Vytisknout výsledek</button><a class="secondary" href="index.html">Zpět na úvodní stránku</a><button id="again" class="secondary">Nový pokus</button></div></section>`;$('#prev').disabled=true;$('#next').disabled=true;$('#pad-toggle').disabled=true;$('#finish').textContent='Výsledek testu';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>go(Number(b.dataset.review)));$('#print').onclick=()=>window.print();$('#again').onclick=()=>{if(window.confirm('Začít nový pokus? Tento výsledek se vymaže.'))location.reload();};$('#question').focus();}
function moveSnail(t,i){if(finished)return;answers['snail'+t]=String(i);selected=t;refreshSnails();renderSteps();$('#announcement').textContent=`Šnek ${t} je u bodu ${i+1}.`;}
function refreshSnails(){document.querySelectorAll('[data-snail]').forEach(el=>{const t=el.dataset.snail,i=answers['snail'+t];el.style.left=(i===undefined?(t==='S'?27:72):points[Number(i)][0]/560*100)+'%';el.style.top=(t==='S'?3:72)+'%';el.classList.remove('dragging');el.classList.toggle('selected',selected===t);el.setAttribute('aria-pressed',String(selected===t));el.setAttribute('aria-label',`Šnek ${t}, ${i===undefined?'zatím neumístěn':'bod '+(Number(i)+1)}`);});$('#snail-status').textContent=snailStatus();}
function nearestPoint(clientX,clientY,r){const x=(clientX-r.left)/r.width*560,y=(clientY-r.top)/r.height*280;let best=-1,dist=Infinity;points.forEach(([px,py],i)=>{const d=Math.hypot(px-x,py+80-y);if(d<dist){dist=d;best=i;}});return dist<=32?best:null;}
function bindSnails(){if(page!==8||finished)return;document.querySelectorAll('[data-point]').forEach(el=>{el.onclick=()=>moveSnail(selected,Number(el.dataset.point));el.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();moveSnail(selected,Number(el.dataset.point));}};});document.querySelectorAll('[data-snail]').forEach(el=>{let drag=null,suppress=false;el.onclick=()=>{if(suppress){suppress=false;return;}selected=el.dataset.snail;refreshSnails();};el.onpointerdown=e=>{if(e.button!==0)return;selected=el.dataset.snail;drag={x:e.clientX,y:e.clientY,moved:false};el.setPointerCapture(e.pointerId);};el.onpointermove=e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4)drag.moved=true;if(!drag.moved)return;const r=$('#snail-board').getBoundingClientRect();el.classList.add('dragging');el.style.left=e.clientX-r.left+'px';el.style.top=e.clientY-r.top-el.offsetHeight/2+'px';};el.onpointerup=e=>{if(!drag)return;const moved=drag.moved;drag=null;suppress=moved;if(moved){const i=nearestPoint(e.clientX,e.clientY,$('#snail-board svg').getBoundingClientRect());if(i!==null)moveSnail(el.dataset.snail,i);else refreshSnails();}else refreshSnails();};el.onpointercancel=()=>{drag=null;refreshSnails();};});}
setInterval(()=>{if(!finished)$('#timer').textContent=formatTime(Math.floor((Date.now()-started)/1000));},1000);render(false);
