'use strict';
const names=['Vítej','Orientace a pravítko','Vyber odpověď','Napiš číslo','Napiš zlomek','Přetáhni šneky','Máš vyzkoušeno'];
const state={step:0,unlocked:0,done:new Set(),choice:'',numbers:{integer:{mode:'plain',value:'',num:'',den:''},fraction:{mode:'plain',value:'',num:'',den:''}},snails:{S:null,T:null},selected:'S',feedback:{}};
const $=s=>document.querySelector(s), escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activeInput=null,rotation=0;
const fractionIcon='<span class="fraction-icon" aria-hidden="true"><span></span><i></i><span></span></span>'; 
const fractionHTML=(a,b)=>`<span class="fraction" aria-label="${a} lomeno ${b}"><span>${a}</span><span>${b}</span></span>`;
function tell(message){$('#announcement').textContent=message;}
function numericValue(model){if(model.mode==='fraction'){if(!/^-?\d+$/.test(model.num)||!/^\d+$/.test(model.den)||Number(model.den)===0)return NaN;return Number(model.num)/Number(model.den);}const s=model.value.trim().replace(',','.');return /^-?\d+(\.\d+)?$/.test(s)?Number(s):NaN;}
function numberField(key){const m=state.numbers[key];return `<div class="answer-wrap"><span id="${key}-label">Odpověď:</span><div class="answer-box">${m.mode==='plain'?`<input id="${key}-value" data-model="${key}" data-part="value" aria-labelledby="${key}-label" type="text" inputmode="decimal" autocomplete="off" maxlength="16" value="${escapeHTML(m.value)}">`:`<div class="fraction-editor"><input id="${key}-num" data-model="${key}" data-part="num" aria-label="Čitatel zlomku" type="text" inputmode="numeric" autocomplete="off" maxlength="8" value="${escapeHTML(m.num)}"><input id="${key}-den" data-model="${key}" data-part="den" aria-label="Jmenovatel zlomku" type="text" inputmode="numeric" autocomplete="off" maxlength="8" value="${escapeHTML(m.den)}"></div>`}</div></div>`;}
function feedbackMarkup(){const f=state.feedback[state.step];return `<p id="feedback" class="feedback ${f&&!f.ok?'error':''}" role="status">${f?escapeHTML(f.text):''}</p>`;}
function updateFeedback(ok,text){state.feedback[state.step]={ok,text};if(ok)state.done.add(state.step);else state.done.delete(state.step);const f=$('#feedback');if(f){f.textContent=text;f.className='feedback'+(ok?'':' error');}renderSteps();}
function clearFeedback(){delete state.feedback[state.step];state.done.delete(state.step);const f=$('#feedback');if(f)f.textContent='';renderSteps();}
function snailBoard(){return `<div class="snail-line" id="snail-line"><svg class="track" viewBox="0 0 600 50" preserveAspectRatio="none" aria-label="Cestička se sedmi body. Hvězdička je nad třetím a praporek pod šestým bodem."><path d="M 0 25 H 600" stroke="#aeb8ca" stroke-width="3"/>${Array.from({length:7},(_,i)=>`<g class="drop-point" data-point="${i}" tabindex="0" role="button" aria-label="Umístit vybraného šneka na bod ${i+1}"><circle class="hit" cx="${i*100}" cy="25" r="24"/><circle cx="${i*100}" cy="25" r="5" fill="#5d6d87"/></g>`).join('')}<text x="200" y="4" text-anchor="middle" fill="#b97212" font-size="23">★</text><text x="500" y="51" text-anchor="middle" fill="#287bb3" font-size="23">⚑</text></svg>${['S','T'].map(t=>`<button class="snail ${state.selected===t?'selected':''}" data-snail="${t}" style="left:${state.snails[t]===null?(t==='S'?18:82):4+state.snails[t]*92/6}%" aria-pressed="${state.selected===t}" aria-label="Šnek ${t}, ${t==='S'?'modrý':'oranžový'}. ${state.snails[t]===null?'Ještě neumístěn.':'Bod '+(state.snails[t]+1)+'.'} Přetáhni jej nebo vyber kliknutím."><img src="assets/snek-${t.toLowerCase()}.png" draggable="false" alt=""><span>${t}</span></button>`).join('')}</div>`;}
const pages=[
()=>`<span class="eyebrow">Než začneš</span><h1>Vítej! Pojď si to vyzkoušet.</h1><p class="lead">Tady zjistíš, jak se test vyplňuje. Všechno si můžeš v klidu osahat.</p><div class="welcome"><div><ul class="welcome-list"><li>Zkusíš vybrat odpověď.</li><li>Napíšeš číslo i zlomek.</li><li>Přesuneš šneky na cestičku.</li></ul><p class="hint">Tady se neznámkuje a čas se neměří. Když se něco nepovede, zkus to znovu.</p></div><img src="assets/snek-s.png" alt="Usměvavý šnek s modrou ulitou"></div><p>Na další obrazovku přejdeš tlačítkem <b>Další krok →</b>. Tlačítkem <b>← Zpět</b> se můžeš vrátit.</p>`,
()=>`<span class="eyebrow">Rozhlédni se</span><h1>Vždy víš, kde právě jsi.</h1><p class="lead">Vlevo vidíš kolečka jednotlivých kroků. Zvýrazněné kolečko ukazuje ten aktuální.</p><p>Na další nový krok postupuješ po jednom. K již otevřeným krokům se můžeš vracet kliknutím na jejich kolečka.</p><div class="row"><span class="clock" aria-label="Ukázka časomíry: dvě minuty patnáct sekund">02:15</span><p class="subtle">Ukázka časomíry.<br>V testu ukáže, jak dlouho už pracuješ.</p></div><div class="exercise"><h2>Vyzkoušej si pravítko</h2><p>Klikni dole na <b>Pravítko</b>. Chytni samotné pravítko a posuň ho. Tažením za značku <b>↻</b> přímo na pravítku ho otočíš.</p><div class="measure" aria-label="Úsečka pro vyzkoušení pravítka"></div><p class="subtle">Přilož nulu pravítka k levému konci úsečky. Konec úsečky najdeš u čísla 4.</p></div>`,
()=>`<span class="eyebrow">Zkus si odpovědět</span><h1>Vyber jednu odpověď.</h1><p class="lead">Klikni na odpověď, kterou považuješ za správnou. Když si to rozmyslíš, klikni na jinou.</p><div class="exercise"><fieldset class="choice-group"><legend>Kolik minut má jedna hodina?</legend>${['12','24','60','120'].map((v,i)=>`<label class="choice"><input type="radio" name="choice" value="${v}" ${state.choice===v?'checked':''}><span class="letter">${'ABCD'[i]}</span><span>${v}</span></label>`).join('')}</fieldset><button class="check" id="check-choice">Zkontrolovat</button>${feedbackMarkup()}</div><p class="subtle">V ostrém testu se správnost odpovědí dozvíš až po odevzdání.</p>`,
()=>`<span class="eyebrow">Číselná klávesnice</span><h1>Napiš číslo.</h1><p class="lead">Klikni do odpovědního políčka. Otevře se číselná klávesnice, kterou můžeš přesouvat za horní lištu.</p><div class="exercise"><h2>Napiš číslo 24.</h2>${numberField('integer')}<button class="check" id="check-integer">Zkontrolovat</button>${feedbackMarkup()}</div><p class="hint">Tlačítkem <b>⌫</b> smažeš znak. <b>OK</b> klávesnici zavře. Můžeš použít i klávesnici počítače.</p><p class="subtle">Číselná klávesnice zadává odpovědi. Výpočty za tebe neprovádí.</p>`,
()=>`<span class="eyebrow">Čitatel a jmenovatel</span><h1>Umíš napsat i zlomek.</h1><p class="lead">Klikni do odpovědního políčka. Potom na číselné klávesnici stiskni tlačítko zlomku <span class="inline-key" role="img" aria-label="Tlačítko zlomku: políčko nad vodorovnou čarou a políčko pod ní">${fractionIcon}</span>. Objeví se dvě políčka nad sebou.</p><div class="exercise"><h2>Napiš zlomek ${fractionHTML(1,2)}.</h2>${numberField('fraction')}<p>Do horního políčka napiš <b>1</b>, do spodního <b>2</b>.</p><button class="check" id="check-fraction">Zkontrolovat</button>${feedbackMarkup()}</div><p class="hint">Horní číslo je <b>čitatel</b>, spodní <b>jmenovatel</b>. Kliknutím vybereš, které právě píšeš.</p>`,
()=>`<span class="eyebrow">Chytni a přesuň</span><h1>Doveď šneky na místo.</h1><p class="lead">Chytni myší obrázek šneka, drž tlačítko a přetáhni ho k bodu. Potom tlačítko pusť.</p><div class="exercise snail-exercise"><p><b>Modrého šneka S</b> přesuň k bodu s <span class="star">★</span> <b>hvězdičkou</b>.<br><b>Oranžového šneka T</b> přesuň k bodu s <b>⚑ praporkem</b>.</p>${snailBoard()}<p class="drag-status" id="drag-status">${snailStatus()}</p><button class="check" id="check-snails">Zkontrolovat</button>${feedbackMarkup()}</div><p class="subtle">Šnek se přichytí k bodu. Můžeš ho přesunout znovu. Také lze kliknout na šneka a pak na bod; klávesnicí použij Tab a Enter.</p>`,
()=>`<span class="eyebrow">Rady máš za sebou</span><div class="finish-mark" aria-hidden="true">✓</div><h1>Teď už víš, jak na to.</h1><p class="lead">V testu si vždy pozorně přečti zadání. Odpověď můžeš před odevzdáním změnit.</p><ul class="summary-list"><li>Mezi otázkami se pohybuj šipkami a kolečky.</li><li>Čísla a zlomky zadávej do odpovědních políček.</li><li>Šneka přetáhni na vybraný bod.</li></ul><p class="hint">Chceš si něco ještě vyzkoušet? Klikni na příslušné kolečko vlevo.</p><div class="row"><button class="secondary" id="repeat">Projít rady znovu</button><a class="secondary tutorial-link" href="../index.html">Zpět na úvodní stránku</a><a class="primary tutorial-link" href="../test.html">Spustit test →</a></div>`
];
function snailStatus(){return ['S','T'].map(t=>`Šnek ${t}: ${state.snails[t]===null?'zatím mimo cestičku':'bod '+(state.snails[t]+1)}`).join(' · ');}
function renderSteps(){const rail=$('#steps');rail.innerHTML=names.map((name,i)=>`<li class="${state.done.has(i)?'done':''}"><button data-step="${i}" ${i>state.unlocked?'disabled':''} ${i===state.step?'aria-current="step"':''} aria-label="Krok ${i+1}: ${name}${state.done.has(i)?', vyzkoušeno':''}"><span class="circle">${i+1}</span><span class="step-name">${name}</span></button></li>`).join('');rail.querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(Number(b.dataset.step)));}
function navigate(i){if(i<0||i>=pages.length||i>state.unlocked)return;closePad();closeRuler();state.step=i;render();}
function render(focus=true){renderSteps();$('#content').innerHTML=pages[state.step]();$('#back').disabled=state.step===0;$('#next').hidden=state.step===6;$('#next').textContent=state.step===5?'Dokončit rady →':'Další krok →';$('#pad-toggle').disabled=![3,4].includes(state.step);$('#ruler-toggle').disabled=state.step!==1;bindPage();if(focus)$('#content').focus();}
$('#back').onclick=()=>navigate(state.step-1);$('#next').onclick=()=>{if([0,1].includes(state.step))state.done.add(state.step);state.unlocked=Math.max(state.unlocked,Math.min(6,state.step+1));navigate(state.step+1);};
function bindPage(){document.querySelectorAll('input[name=choice]').forEach(el=>el.onchange=()=>{state.choice=el.value;clearFeedback();});const choice=$('#check-choice');if(choice)choice.onclick=()=>updateFeedback(state.choice==='60',state.choice==='60'?'Správně! Hodina má 60 minut.':state.choice?'Zkus to znovu. Vzpomeň si na hodiny.':'Nejprve vyber jednu odpověď.');
bindNumberFields();for(const key of ['integer','fraction']){const btn=$('#check-'+key);if(btn)btn.onclick=()=>{const v=numericValue(state.numbers[key]);const target=key==='integer'?24:.5;let ok=Number.isFinite(v)&&Math.abs(v-target)<1e-10;closePad();updateFeedback(ok,ok?(key==='integer'?'Správně, napsal/a jsi 24.':state.numbers.fraction.mode==='fraction'?'Správně! Tento zlomek představuje polovinu.':'Správně, toto číslo představuje polovinu. Vyzkoušej si ještě tlačítko zlomku.'):'Ještě to není ono. Zkontroluj zadané číslice a zkus to znovu.');};}
if(state.step===5)bindSnails();if($('#repeat'))$('#repeat').onclick=()=>navigate(0);}
function bindNumberFields(){document.querySelectorAll('[data-model]').forEach(input=>{input.onfocus=()=>openPad(input);input.onclick=()=>openPad(input);input.oninput=()=>{state.numbers[input.dataset.model][input.dataset.part]=input.value;clearFeedback();};});}
function openPad(input){if(!input)return;activeInput=input;$('#keypad').hidden=false;$('#pad-toggle').setAttribute('aria-pressed','true');$('#pad-target').textContent=input.dataset.part==='num'?'Píšeš čitatele (horní číslo).':input.dataset.part==='den'?'Píšeš jmenovatele (spodní číslo).':'Píšeš do odpovědního pole.';clampFloating($('#keypad'));}
function closePad(){ $('#keypad').hidden=true;$('#pad-toggle').setAttribute('aria-pressed','false');activeInput=null;}
$('#pad-toggle').onclick=()=>{if(!$('#keypad').hidden){closePad();return;}const el=$('[data-model]');if(el){el.focus();openPad(el);}};$('#pad-close').onclick=closePad;
const keys=[['7','7'],['8','8'],['9','9'],['minus','−'],['4','4'],['5','5'],['6','6'],['fraction',fractionIcon],['1','1'],['2','2'],['3','3'],['back','⌫'],['0','0'],['comma',','],['ok','OK']];$('#keys').innerHTML=keys.map(([k,label])=>`<button data-key="${k}" aria-label="${k==='fraction'?'Zadat zlomek':k==='back'?'Smazat znak':k==='ok'?'Zavřít klávesnici':k==='minus'?'Znaménko minus':k==='comma'?'Desetinná čárka':label}">${label}</button>`).join('');
$('#keys').querySelectorAll('button').forEach(b=>{b.onpointerdown=e=>e.preventDefault();b.onclick=()=>keyPress(b.dataset.key);});
function keyPress(key){if(key==='ok'){closePad();return;}if(!activeInput||!document.contains(activeInput))return;const input=activeInput,m=state.numbers[input.dataset.model];
if(key==='fraction'){const which=input.dataset.model;if(m.mode==='fraction'){$(`[data-model="${which}"][data-part="num"]`).focus();return;}m.num=/^-?\d+$/.test(m.value)?m.value:'';m.den='';m.mode='fraction';const wrap=input.closest('.answer-wrap');wrap.outerHTML=numberField(which);bindNumberFields();$(`[data-model="${which}"]`).focus();clearFeedback();return;}
const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;let value=input.value,pos=start;
if(key==='back'){if(start!==end){value=value.slice(0,start)+value.slice(end);}else if(start>0){value=value.slice(0,start-1)+value.slice(end);pos--;} }
else if(key==='minus'){if(input.dataset.part==='den')return;value=value.startsWith('-')?value.slice(1):'-'+value;pos=value.length;}
else{const ch=key==='comma'?',':key;if(ch===','&&(m.mode==='fraction'||/[,.]/.test(value)))return;if(value.length>=input.maxLength&&start===end)return;value=value.slice(0,start)+ch+value.slice(end);pos=start+ch.length;}
input.value=value;input.setSelectionRange(Math.max(0,pos),Math.max(0,pos));m[input.dataset.part]=value;clearFeedback();}
function closeRuler(){$('#ruler').hidden=true;$('#ruler-toggle').setAttribute('aria-pressed','false');}
$('#ruler-toggle').onclick=()=>{if(state.step!==1)return;const r=$('#ruler');r.hidden=!r.hidden;$('#ruler-toggle').setAttribute('aria-pressed',String(!r.hidden));if(!r.hidden){rotation=0;applyRulerAngle();clampFloating(r);}};$('#ruler-close').onclick=closeRuler;
$('#ruler-scale').innerHTML=`<rect x="0" y="0" width="440" height="72" fill="transparent"/>${Array.from({length:101},(_,i)=>{const x=10+i*4.2;return `<line x1="${x}" y1="0" x2="${x}" y2="${i%10===0?23:i%5===0?17:10}" stroke="#66552f" stroke-width="1"/>${i%10===0?`<text x="${x}" y="39" text-anchor="middle" fill="#584823" font-size="12">${i/10}</text>`:''}`;}).join('')}<text x="220" y="61" text-anchor="middle" font-size="12" fill="#584823">centimetry</text>`;
function applyRulerAngle(){ $('#ruler').style.transform=`rotate(${rotation}deg)`; }
const ruler=$('#ruler'),rotator=$('#ruler-rotate');let rulerDrag=null,turn=null;
$('#ruler-scale').onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();rulerDrag={x:e.clientX,y:e.clientY,left:ruler.offsetLeft,top:ruler.offsetTop};e.currentTarget.setPointerCapture(e.pointerId);};
$('#ruler-scale').onpointermove=e=>{if(!rulerDrag)return;ruler.style.left=Math.max(8,Math.min(innerWidth-ruler.offsetWidth-8,rulerDrag.left+e.clientX-rulerDrag.x))+'px';ruler.style.top=Math.max(8,Math.min(innerHeight-ruler.offsetHeight-8,rulerDrag.top+e.clientY-rulerDrag.y))+'px';};
$('#ruler-scale').onpointerup=$('#ruler-scale').onpointercancel=()=>{rulerDrag=null;};
$('#ruler-scale').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();ruler.style.left=Math.max(8,Math.min(innerWidth-ruler.offsetWidth-8,ruler.offsetLeft+(e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0)))+'px';ruler.style.top=Math.max(8,Math.min(innerHeight-ruler.offsetHeight-8,ruler.offsetTop+(e.key==='ArrowUp'?-10:e.key==='ArrowDown'?10:0)))+'px';};
rotator.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const r=ruler.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;turn={cx,cy,start:Math.atan2(e.clientY-cy,e.clientX-cx),angle:rotation};rotator.setPointerCapture(e.pointerId);};
rotator.onpointermove=e=>{if(!turn)return;rotation=turn.angle+(Math.atan2(e.clientY-turn.cy,e.clientX-turn.cx)-turn.start)*180/Math.PI;applyRulerAngle();};
rotator.onpointerup=rotator.onpointercancel=()=>{turn=null;};
rotator.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home'].includes(e.key)){e.preventDefault();rotation=e.key==='Home'?0:rotation+(e.key==='ArrowLeft'?-5:5);applyRulerAngle();}};
function clampFloating(el){if(el.hidden)return;const r=el.getBoundingClientRect();el.style.left=Math.max(5,Math.min(r.left,innerWidth-r.width-5))+'px';el.style.top=Math.max(5,Math.min(r.top,innerHeight-r.height-5))+'px';el.style.right='auto';}
function dragPanel(panel,handle){let drag=null;handle.onpointerdown=e=>{if(e.button!==0)return;const r=panel.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};handle.setPointerCapture(e.pointerId);};handle.onpointermove=e=>{if(!drag)return;panel.style.left=e.clientX-drag.x+'px';panel.style.top=e.clientY-drag.y+'px';panel.style.right='auto';clampFloating(panel);};handle.onpointerup=handle.onpointercancel=()=>{drag=null;};handle.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const r=panel.getBoundingClientRect();panel.style.left=r.left+(e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0)+'px';panel.style.top=r.top+(e.key==='ArrowUp'?-10:e.key==='ArrowDown'?10:0)+'px';clampFloating(panel);};}
dragPanel($('#keypad'),$('#pad-handle'));window.addEventListener('resize',()=>{clampFloating($('#ruler'));clampFloating($('#keypad'));});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePad();closeRuler();}});
function snapIndex(x,y,rect){const relX=(x-rect.left)/rect.width;if(y<rect.top-38||y>rect.bottom+38||relX<-.05||relX>1.05)return null;return Math.max(0,Math.min(6,Math.round(relX*6)));}
function moveSnail(t,i){state.snails[t]=i;state.selected=t;clearFeedback();refreshSnails();tell(`Šnek ${t} je u bodu ${i+1}.`);}
function refreshSnails(){document.querySelectorAll('[data-snail]').forEach(el=>{const t=el.dataset.snail;el.style.left=(state.snails[t]===null?(t==='S'?18:82):4+state.snails[t]*92/6)+'%';el.style.top='';el.classList.remove('dragging');el.classList.toggle('selected',state.selected===t);el.setAttribute('aria-pressed',String(state.selected===t));el.setAttribute('aria-label',`Šnek ${t}. ${state.snails[t]===null?'Ještě neumístěn.':'Bod '+(state.snails[t]+1)+'.'} Přetáhni jej nebo vyber kliknutím.`);});$('#drag-status').textContent=snailStatus();}
function bindSnails(){document.querySelectorAll('[data-snail]').forEach(el=>{let drag=null,suppress=false;el.onclick=()=>{if(suppress){suppress=false;return;}state.selected=el.dataset.snail;refreshSnails();};el.onpointerdown=e=>{if(e.button!==0)return;state.selected=el.dataset.snail;drag={x:e.clientX,y:e.clientY,moved:false};el.setPointerCapture(e.pointerId);el.classList.add('selected');};el.onpointermove=e=>{if(!drag)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4)drag.moved=true;if(!drag.moved)return;const r=$('#snail-line').getBoundingClientRect();el.classList.add('dragging');el.style.left=e.clientX-r.left+'px';el.style.top=e.clientY-r.top-40+'px';};el.onpointerup=e=>{if(!drag)return;const moved=drag.moved;drag=null;suppress=moved;if(moved){const idx=snapIndex(e.clientX,e.clientY,$('.track').getBoundingClientRect());if(idx!==null)moveSnail(el.dataset.snail,idx);else{refreshSnails();tell('Pusť šneka blíž k cestičce.');}}else refreshSnails();};el.onpointercancel=()=>{drag=null;refreshSnails();};});document.querySelectorAll('[data-point]').forEach(el=>{el.onclick=()=>moveSnail(state.selected,Number(el.dataset.point));el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();moveSnail(state.selected,Number(el.dataset.point));}};});$('#check-snails').onclick=()=>{const ok=state.snails.S===2&&state.snails.T===5;updateFeedback(ok,ok?'Výborně! Oba šneci jsou na správných místech.':'Podívej se na hvězdičku a praporek. Oba šneky můžeš znovu přesunout.');};}
render(false);
